### ISSUE TITLE
Array overwrite in InitNormal

### ISSUE THREAD

**Issue by mcflugen** [csdms-contrib/cem#6]
@plimber, @haileyajohnson:

`InitNormal` writes past the end of the `TypeOfRock` and `topography` arrays when setting fast and slow weathering portions.

``` c
for (x = 0; x < X_MAX; x++) {
  for (n = 0; n <= 2 * NUMBER_CHUNK; n++) {
    for (y = n * CHUNK_LENGTH; y < ((n + 2) * CHUNK_LENGTH); y++) {
      if (n % 3 == 0 && (!blocks || x > InitialRock - 3)) { // if even
        TypeOfRock[x][y] = 's';
        topography[x][y] = kCliffHeightSlow;
      }
      else { // if odd
        TypeOfRock[x][y] = 'f';
        topography[x][y] = kCliffHeightFast;
      }
    }
}
```

Depending on the values for `NUMBER_CHUNK` and `CHUNK_LENGTH`, `y` will eventually be larger than `2 * Y_MAX`, which is the number of columns for the arrays in question.

I propose that the length of each chunk be calculated based on `Y_MAX` and the number of chunks (`NUMBER_CHUNK`). I suppose the opposite would also work: calculate the number of chunks based on the number of columns and the chunk length. We will also have to do something with partial chunks if the number of columns isn't a multiple of the length of chunks.

The other thing is that the code within the innermost loop doesn't appear to do what the comments suggest (`n % 3` doesn't test for even/odd) and overwrites data right after it's been initialized (perhaps `n++` should be `n+=2`?).

**Comment by plimber** [comment]
You are correct about the chunk length -- should be calculated based on Y_max and NUMBER_CHUNK.

And i think you are also right about n++ versus n+=2...

**Comment by mcflugen** [comment]
Thanks @plimber, @haileyajohnson. I've fixed this now. The only difference is that now there are equal amounts of slow and fast weathering rock bands. So,
    `sssfffsssfffsssfff`
rather than
    `sssffffffsssffffff`

@plimber: I guess this should also be set up for period boundary conditions, is that right? It wasn't before but I think that was probably a mistake.
